<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => 'marketing_',
	'db_port' => '3306',
	'db_name' => 'marketing',
	'db_user' => 'root',
	'db_password' => 'Bags6044',
	'db_server_version' => '5.7.13-0ubuntu0.16.04.2',
	'mailer_from_name' => 'Brian Bagdasarian',
	'mailer_from_email' => 'brian@buildabigidea.com',
	'mailer_transport' => 'smtp',
	'mailer_host' => 'smtp.mandrillapp.com',
	'mailer_port' => '587',
	'mailer_user' => 'Obii',
	'mailer_password' => 'k1IHMRL3BO-riL0utlYbPQ',
	'mailer_encryption' => null,
	'mailer_auth_mode' => 'login',
	'mailer_spool_type' => 'file',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '59ef05bed5068fe5370ba1df8e713d7841e2209ca53fe80e822c07ea8746fe9e',
	'site_url' => 'http://marketing.buildabigidea.com/index.php',
	'webroot' => null,
	'cache_path' => '/var/www/html/app/cache',
	'log_path' => '/var/www/html/app/logs',
	'image_path' => 'media/images',
	'theme' => 'nature',
	'locale' => 'en_US',
	'trusted_hosts' => array(

	),
	'trusted_proxies' => array(

	),
	'rememberme_key' => 'f8b9c434d19bb07bd972924b55ace13248ff64e0',
	'rememberme_lifetime' => '31536000',
	'rememberme_path' => '/',
	'rememberme_domain' => null,
	'default_pagelimit' => 30,
	'default_timezone' => 'America/New_York',
	'date_format_full' => 'F j, Y g:i a T',
	'date_format_short' => 'D, M d',
	'date_format_dateonly' => 'F j, Y',
	'date_format_timeonly' => 'g:i a',
	'ip_lookup_service' => 'maxmind_download',
	'ip_lookup_auth' => null,
	'ip_lookup_config' => array(

	),
	'update_stability' => 'stable',
	'cookie_path' => '/',
	'cookie_domain' => 'buildabigidea.com',
	'cookie_secure' => false,
	'cookie_httponly' => false,
	'do_not_track_ips' => array(

	),
	'do_not_track_internal_ips' => array(

	),
	'link_shortener_url' => null,
	'cached_data_timeout' => '10',
	'batch_sleep_time' => 1,
	'batch_campaign_sleep_time' => false,
	'cors_restrict_domains' => false,
	'cors_valid_domains' => array(
		"0" => "http://www.buildabigidea.com"
	),
	'api_enabled' => true,
	'api_oauth2_access_token_lifetime' => 60,
	'api_oauth2_refresh_token_lifetime' => 14,
	'upload_dir' => '/var/www/html/app/../media/files',
	'max_size' => '6',
	'allowed_extensions' => array(
		"0" => "csv", 
		"1" => "doc", 
		"2" => "docx", 
		"3" => "epub", 
		"4" => "gif", 
		"5" => "jpg", 
		"6" => "jpeg", 
		"7" => "mpg", 
		"8" => "mpeg", 
		"9" => "mp3", 
		"10" => "odt", 
		"11" => "odp", 
		"12" => "ods", 
		"13" => "pdf", 
		"14" => "png", 
		"15" => "ppt", 
		"16" => "pptx", 
		"17" => "tif", 
		"18" => "tiff", 
		"19" => "txt", 
		"20" => "xls", 
		"21" => "xlsx", 
		"22" => "wav"
	),
	'campaign_time_wait_on_event_false' => 'PT1H',
	'mailer_return_path' => 'marketing.bounce@buildabigidea.com',
	'mailer_append_tracking_pixel' => true,
	'mailer_convert_embed_images' => true,
	'mailer_amazon_region' => 'email-smtp.us-east-1.amazonaws.com',
	'mailer_spool_msg_limit' => '1000',
	'mailer_spool_time_limit' => null,
	'mailer_spool_recover_timeout' => '900',
	'mailer_spool_clear_timeout' => '1800',
	'unsubscribe_text' => '<a href=\'|URL|\'>Unsubscribe</a> to no longer receive emails from us.',
	'webview_text' => '<a href=\'|URL|\'>Having trouble reading this email? Click here.</a>',
	'unsubscribe_message' => 'We are sorry to see you go! |EMAIL| will no longer receive emails from us. If this was by mistake, <a href=\'|URL|\'>click here to re-subscribe</a>.',
	'resubscribe_message' => '|EMAIL| has been re-subscribed. If this was by mistake, <a href=\'|URL|\'>click here to unsubscribe</a>.',
	'monitored_email' => array(
		"general" => array(
			"address" => "marketing.bouce@buildabigidea.com", 
			"host" => "imap.gmail.com", 
			"port" => "993", 
			"encryption" => "/ssl", 
			"user" => "marketing.bounce@brianbagdasarian.com", 
			"password" => "Bags6044"
		), 
		"EmailBundle_bounces" => array(
			"address" => "", 
			"host" => "", 
			"port" => "993", 
			"encryption" => "/ssl", 
			"user" => "", 
			"password" => "", 
			"override_settings" => "", 
			"folder" => "INBOX", 
			"ssl" => "1"
		), 
		"EmailBundle_unsubscribes" => array(
			"address" => "", 
			"host" => "", 
			"port" => "993", 
			"encryption" => "/ssl", 
			"user" => "", 
			"password" => "", 
			"override_settings" => "", 
			"folder" => "INBOX", 
			"ssl" => "1"
		)
	),
	'mailer_is_owner' => false,
	'default_signature_text' => 'Best regards, |FROM_NAME|',
	'notification_enabled' => true,
	'notification_app_id' => 'ec65f125-8bfb-4a2f-a3a2-47be7fcbe74c',
	'notification_rest_api_key' => 'MWNlMmVhNDctZGM3Yi00MzZmLThiODktOTM3MjRjMDY5Y2Nm',
	'notification_safari_web_id' => 'web.onesignal.auto.571cab93-0309-4674-850d-02fe7b657956',
	'cat_in_page_url' => false,
	'google_analytics' => null,
	'redirect_list_types' => array(
		"301" => "mautic.page.form.redirecttype.permanent", 
		"302" => "mautic.page.form.redirecttype.temporary"
	),
	'sms_enabled' => true,
	'sms_username' => 'AC104a05fbc0fd002840d3454001207082',
	'sms_password' => '29bb15be90c9dfba2111aedc2ac11013',
	'sms_sending_phone_number' => '+12078353338',
	'webhook_start' => 0,
	'webhook_limit' => 1000,
	'webhook_log_max' => 10,
	'queue_mode' => 'immediate_process',
	'twitter_handle_field' => 'twitter',
);
